#!/usr/bin/env node
// Single source of truth for branding: `brand/<id>/brand.json` plus the
// official assets next to it. This script projects one brand into every
// place the app reads it, so no name, identifier, colour, or icon is written
// by hand anywhere else:
//
//   src/renderer/generated/          brand.ts, app/tray icons, and wordmark SVGs
//   gateway/src/brand.rs              Rust constants (tray, menus, data dir)
//   src-tauri/tauri.brand.conf.json   Tauri config overlay (ignored; passed as --config)
//   src-tauri/icons/                  the five desktop icons the bundle lists
//   assets/tray/trayTemplate*.png     monochrome template tray icon
//
// The default brand is `dstack`; `PRIVATE_AI_GATEWAY_BRAND=<id>` selects
// another. The renderer module, the Rust module, the desktop icons, and the
// tray icon are committed for the default brand and CI fails on drift; the
// Tauri overlay is regenerated on every run and merged by the CLI, so the
// tracked tauri.conf.json stays neutral. Every check here fails fast, before
// anything is written: a missing asset or field is an error, never a silent
// fallback.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { copyFile, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { Resvg } from "@resvg/resvg-js";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const brandId = process.env.PRIVATE_AI_GATEWAY_BRAND ?? "dstack";
/** The icon files the desktop bundle actually ships (tauri.conf.json bundle.icon). */
const DESKTOP_ICONS = ["32x32.png", "128x128.png", "128x128@2x.png", "icon.icns", "icon.ico"];
if (!/^[a-z][a-z0-9-]*$/.test(brandId)) {
  throw new Error(`PRIVATE_AI_GATEWAY_BRAND must be a lowercase id, got ${JSON.stringify(brandId)}`);
}
const brandDir = path.join(appRoot, "brand", brandId);
const brand = JSON.parse(await readFile(path.join(brandDir, "brand.json"), "utf8"));

const required = {
  id: "string",
  productName: "string",
  shortName: "string",
  organizationName: "string",
  tagline: "string",
  homepageUrl: "string",
  supportUrl: "string",
  "service.name": "string",
  "service.defaultUrl": "string",
  "service.keyLabel": "string",
  "bundle.identifier": "string",
  "bundle.category": "string",
  "bundle.shortDescription": "string",
  "bundle.longDescription": "string",
  "theme.accentLight": "color",
  "theme.accentDark": "color",
  "theme.brandColor": "color",
  "theme.iconBackground": "color",
  "assets.appIconMark": "file",
  "assets.trayTemplate": "file",
  "assets.wordmarkLight": "file",
  "assets.wordmarkDark": "file",
};
const optional = {
  "theme.iconBackgroundLight": "color",
  "theme.iconBackgroundDark": "color",
  "assets.appIconLightMark": "file",
  "assets.appIconDarkMark": "file",
};
const problems = [];
for (const [key, kind] of Object.entries(required)) {
  const value = key.split(".").reduce((node, part) => node?.[part], brand);
  if (typeof value !== "string" || !value.trim()) {
    problems.push(`${key} is missing`);
  } else if (kind === "color" && !/^#[0-9a-f]{6}$/i.test(value)) {
    problems.push(`${key} must be a #rrggbb colour`);
  } else if (kind === "file" && !(await exists(path.join(brandDir, value)))) {
    problems.push(`${key} points at ${value}, which is not in ${brandDir}`);
  }
}
for (const [key, kind] of Object.entries(optional)) {
  const value = key.split(".").reduce((node, part) => node?.[part], brand);
  if (value === undefined) {
    continue;
  }
  if (typeof value !== "string" || !value.trim()) {
    problems.push(`${key} must be a non-empty string when provided`);
  } else if (kind === "color" && !/^#[0-9a-f]{6}$/i.test(value)) {
    problems.push(`${key} must be a #rrggbb colour`);
  } else if (kind === "file" && !(await exists(path.join(brandDir, value)))) {
    problems.push(`${key} points at ${value}, which is not in ${brandDir}`);
  }
}
if (brand.id !== brandId) {
  problems.push(`brand.json id ${JSON.stringify(brand.id)} does not match directory ${brandId}`);
}
if (!/^[a-z][a-z0-9-]*(\.[a-z][a-z0-9-]*)+$/i.test(brand.bundle?.identifier ?? "")) {
  problems.push("bundle.identifier must be reverse-DNS");
}
for (const [file, digest] of Object.entries(brand.source?.sha256 ?? {})) {
  const actual = createHash("sha256").update(await readFile(path.join(brandDir, file))).digest("hex");
  if (actual !== digest) {
    problems.push(`${file} does not match its recorded sha256 (${actual})`);
  }
}
if (problems.length > 0) {
  throw new Error(`Brand ${brandId} is not buildable:\n  ${problems.join("\n  ")}`);
}

const asset = (name) => readFile(path.join(brandDir, brand.assets[name]), "utf8");
const generatedNote = `Generated by scripts/prepare-brand.mjs from brand/${brandId}/brand.json. Do not edit.`;
const appIconLightMark = await readFile(
  path.join(brandDir, brand.assets.appIconLightMark ?? brand.assets.appIconMark),
  "utf8",
);
const appIconDarkMark = await readFile(
  path.join(brandDir, brand.assets.appIconDarkMark ?? brand.assets.appIconMark),
  "utf8",
);
const appIconLightSvg = composeAppIcon(
  appIconLightMark,
  brand.theme.iconBackgroundLight ?? brand.theme.iconBackground,
);
const appIconDarkSvg = composeAppIcon(
  appIconDarkMark,
  brand.theme.iconBackgroundDark ?? brand.theme.iconBackground,
);

// --- renderer -------------------------------------------------------------
// Renderer images are generated next to the module and imported as Vite assets,
// so they ship as self-hosted files under the production CSP (`img-src 'self'`,
// no `data:`).
const generatedDir = path.join(appRoot, "src/renderer/generated");
await mkdir(generatedDir, { recursive: true });
await writeFile(path.join(generatedDir, "app-icon-light.svg"), appIconLightSvg);
await writeFile(path.join(generatedDir, "app-icon-dark.svg"), appIconDarkSvg);
await copyFile(path.join(brandDir, brand.assets.trayTemplate), path.join(generatedDir, "tray-mark.svg"));
await copyFile(path.join(brandDir, brand.assets.wordmarkLight), path.join(generatedDir, "wordmark-light.svg"));
await copyFile(path.join(brandDir, brand.assets.wordmarkDark), path.join(generatedDir, "wordmark-dark.svg"));
const rendererBrand = {
  id: brand.id,
  productName: brand.productName,
  shortName: brand.shortName,
  organizationName: brand.organizationName,
  tagline: brand.tagline,
  homepageUrl: brand.homepageUrl,
  supportUrl: brand.supportUrl,
  service: brand.service,
  theme: brand.theme,
};
await writeFile(
  path.join(generatedDir, "brand.ts"),
  `// ${generatedNote}
import appIconDark from "./app-icon-dark.svg";
import appIconLight from "./app-icon-light.svg";
import wordmarkDark from "./wordmark-dark.svg";
import wordmarkLight from "./wordmark-light.svg";

export const brand = {
  ...${JSON.stringify(rendererBrand, null, 2).replace(/\n/g, "\n  ")},
  appIcon: { light: appIconLight, dark: appIconDark },
  wordmark: { light: wordmarkLight, dark: wordmarkDark },
} as const;
`,
);

// --- Rust -----------------------------------------------------------------
const rust = (value) => JSON.stringify(value);
await writeFile(
  path.join(appRoot, "gateway/src/brand.rs"),
  `//! ${generatedNote}

pub const ID: &str = ${rust(brand.id)};
pub const PRODUCT_NAME: &str = ${rust(brand.productName)};
pub const SHORT_NAME: &str = ${rust(brand.shortName)};
pub const ORGANIZATION_NAME: &str = ${rust(brand.organizationName)};
pub const TAGLINE: &str = ${rust(brand.tagline)};
pub const HOMEPAGE_URL: &str = ${rust(brand.homepageUrl)};
pub const SUPPORT_URL: &str = ${rust(brand.supportUrl)};
pub const SERVICE_NAME: &str = ${rust(brand.service.name)};
pub const SERVICE_DEFAULT_URL: &str = ${rust(brand.service.defaultUrl)};
/// Bundle identifier; names the per-user app data directory on every platform.
pub const APP_IDENTIFIER: &str = ${rust(brand.bundle.identifier)};
`,
);

// --- Tauri config overlay ---------------------------------------------------
// Merged by `tauri dev|build --config` (RFC 7396: objects merge, arrays are
// replaced), and exported by the CLI as TAURI_CONFIG so the compiled context
// carries the same values. Only scalar product metadata goes here; the window
// list stays in the tracked config, and the window title is set at run time
// from the Rust brand module.
await writeFile(
  path.join(appRoot, "src-tauri/tauri.brand.conf.json"),
  `${JSON.stringify(
    {
      productName: brand.productName,
      identifier: brand.bundle.identifier,
      bundle: {
        category: brand.bundle.category,
        shortDescription: brand.bundle.shortDescription,
        longDescription: brand.bundle.longDescription,
        publisher: brand.organizationName,
        homepage: brand.homepageUrl,
      },
    },
    null,
    2,
  )}\n`,
);

// --- icons ------------------------------------------------------------------
// App icon: the official mark centred on a brand-coloured rounded square
// (macOS icon grid: 1024 canvas, 824 shape, 232 corner radius). The mark is
// embedded unchanged.
const scratch = path.join(appRoot, "brand/.generated");
await rm(scratch, { recursive: true, force: true });
await mkdir(scratch, { recursive: true });
const appIconPng = path.join(scratch, "app-icon.png");
await writeFile(appIconPng, render(appIconDarkSvg, 1024));
// `tauri icon` renders every platform; only the desktop files the bundle
// lists (tauri.conf.json `bundle.icon`) are copied into the tracked set.
const iconSet = path.join(scratch, "icons");
execFileSync(process.execPath, [path.join(appRoot, "node_modules/@tauri-apps/cli/tauri.js"), "icon", appIconPng, "-o", iconSet], { stdio: "ignore" });
for (const file of DESKTOP_ICONS) {
  const source = path.join(iconSet, file);
  const target = path.join(appRoot, "src-tauri/icons", file);
  if (file === "icon.icns") {
    // `tauri icon` writes the icns entries in hash order; sort them so the
    // tracked file is byte-for-byte reproducible.
    await writeFile(target, normalizeIcns(await readFile(source)));
  } else {
    await copyFile(source, target);
  }
}

// Menu bar: a monochrome template of the official mark (alpha only; macOS
// tints it), never the coloured logo.
const tray = await asset("trayTemplate");
const trayDir = path.join(appRoot, "assets/tray");
await mkdir(trayDir, { recursive: true });
await writeFile(path.join(trayDir, "trayTemplate.png"), render(tray, 18));
await writeFile(path.join(trayDir, "trayTemplate@2x.png"), render(tray, 36));
await rm(scratch, { recursive: true, force: true });

console.log(`Prepared brand ${brandId}: ${brand.productName} (${brand.bundle.identifier})`);

/** An ICNS file is a header plus (type, length, data) entries; order is free. */
function normalizeIcns(buffer) {
  if (buffer.toString("latin1", 0, 4) !== "icns") {
    throw new Error("tauri icon did not produce an icns file");
  }
  const entries = [];
  for (let offset = 8; offset < buffer.length; ) {
    const length = buffer.readUInt32BE(offset + 4);
    entries.push(buffer.subarray(offset, offset + length));
    offset += length;
  }
  entries.sort((a, b) => a.compare(b, 0, 4, 0, 4));
  return Buffer.concat([buffer.subarray(0, 8), ...entries]);
}

function render(svg, size) {
  return new Resvg(svg, { fitTo: { mode: "width", value: size } }).render().asPng();
}

function composeAppIcon(mark, background) {
  const { width, height } = svgSize(mark);
  const inset = 824 * 0.62;
  const scale = inset / Math.max(width, height);
  const offsetX = 512 - (width * scale) / 2;
  const offsetY = 512 - (height * scale) / 2;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
<rect x="100" y="100" width="824" height="824" rx="185" fill="${background}"/>
<g transform="translate(${offsetX.toFixed(2)} ${offsetY.toFixed(2)}) scale(${scale.toFixed(4)})">${inner(mark)}</g>
</svg>`;
}

function svgSize(svg) {
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]?.trim().split(/[\s,]+/).map(Number);
  if (viewBox?.length === 4) {
    return { width: viewBox[2], height: viewBox[3] };
  }
  const width = Number(svg.match(/\swidth="([\d.]+)"/)?.[1]);
  const height = Number(svg.match(/\sheight="([\d.]+)"/)?.[1]);
  if (!width || !height) {
    throw new Error("The app icon mark needs a viewBox or width/height");
  }
  return { width, height };
}

function inner(svg) {
  const open = svg.indexOf(">", svg.indexOf("<svg"));
  const close = svg.lastIndexOf("</svg>");
  if (open < 0 || close < 0) {
    throw new Error("The app icon mark is not an SVG document");
  }
  return svg.slice(open + 1, close);
}

async function exists(file) {
  try {
    await readFile(file);
    return true;
  } catch {
    return false;
  }
}
